In [42]:
# IRIS MODEL COMPARISON
# LOGISTIC REGRESSION, KNN=1, KNN=5


In [43]:
# Step 1 Import load_iris function from datasets module
from sklearn.datasets import load_iris
iris = load_iris()
type(iris)
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [44]:
# Step 2 - Explore iris dataset
print(iris.feature_names)
print(iris.target)
print(iris.target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [45]:
# Step 3 Check data types and shapes
print(type(iris.data))
print(type(iris.target))
print("iris.data", iris.data.shape)
print("iris.target", iris.target.shape)


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
iris.data (150, 4)
iris.target (150,)


In [46]:
# Step 4 Create X, y - X_train, X_test, y_train, y_test
X = iris.data
y = iris.target
print(X.shape)
print(y.shape)

# Split into train and test sets

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=4)

# print shapes of new X objects
print("X_train shape", X_train.shape)
print("X_test shape", X_test.shape)

# print shapes of new y objects
print("y_train shape", y_train.shape)
print("y_test shape", y_test.shape)


(150, 4)
(150,)
X_train shape (90, 4)
X_test shape (60, 4)
y_train shape (90,)
y_test shape (60,)


In [47]:
# Step 5 Modelling pattern (ML)
# Scikit learn provides a uniform interface to ML models
# All models can follow same 4 steps

# Model 1 - Logistic Regression
#---------------------------------

# 5A Import
#-------------
from sklearn.linear_model import LogisticRegression

# 5B Instantiate
#-----------------
logreg = LogisticRegression(max_iter=200)

# 5C Fit with data / Train
#--------------------------
logreg.fit(X_train,y_train)

# 5D Predict
#-------------
y_pred = logreg.predict(X_test)
print("predict_value", y_pred)


predict_value [2 0 2 2 2 1 2 0 0 2 0 0 0 1 2 0 1 0 0 2 0 2 1 0 0 0 0 0 0 2 1 0 2 0 1 2 2
 1 1 0 2 0 1 0 2 0 0 1 1 2 0 1 2 2 1 1 0 1 1 1]


In [48]:
# Step 6 Evaluation from sklearn.metrics
# Compare y_pred with actual values which is y_test

from sklearn.metrics import accuracy_score
acc_score = (accuracy_score(y_test,y_pred))
print("Logistic Regression Model Accuracy", acc_score)


Logistic Regression Model Accuracy 0.9666666666666667


REPEAT STEP 5 AND STEP 6 FOR MODEL WITH KNN=1 AND KNN=5

In [49]:
# Model 2 - KNN=5
#--------------------------------------------------------
# 1. Import, 2. Instantiate 3. Fit 4. Predict 5. Evaluate
#--------------------------------------------------------
#Import
from sklearn.neighbors import KNeighborsClassifier
#Instantiate
knn = KNeighborsClassifier(n_neighbors=5)
#Fit
knn.fit(X_train,y_train)
#Predict
y_pred = knn.predict(X_test)
#Evaluate
acc_score = (accuracy_score(y_test,y_pred))
print("KNN=5 Model Accuracy", acc_score)


KNN=5 Model Accuracy 0.9666666666666667


In [50]:
# Model 3 - KNN=1
#--------------------------------------------------------
# 1. Import, 2. Instantiate 3. Fit 4. Predict 5. Evaluate
#--------------------------------------------------------
#Import
from sklearn.neighbors import KNeighborsClassifier
#Instantiate
knn = KNeighborsClassifier(n_neighbors=1)
#Fit
knn.fit(X_train,y_train)
#Predict
y_pred = knn.predict(X_test)
#Evaluate
acc_score = (accuracy_score(y_test,y_pred))
print("KNN=1 Model Accuracy", acc_score)



KNN=1 Model Accuracy 0.95
